### ISSUE TITLE
ln: failed to create symbolic link '/home/printer/klipper_config/addons/timelapse.cfg': No such file or directory

### ISSUE THREAD

**Issue by kennethjiang** [mainsail-crew/virtual-klipper-printer#12]
I pulled the latest and now the `printer` container will quit for this error:

```
printer  | ###[22:51:04]: Check folders permissions ...
printer  | ###[22:51:04]: chown for user: 'printer' on folder: /home/printer/timelapse
printer  | ###[22:51:04]: OK!
printer  | ###[22:51:04]: Linking moonraker-timelapse component ...
printer  | ###[22:51:04]: OK!
printer  | ###[22:51:04]: Linking timelapse.cfg ...
printer  | ln: failed to create symbolic link '/home/printer/klipper_config/addons/timelapse.cfg': No such file or directory
```

It looks the file `timelapse.cfg` is missing from the folder `printer_storage/timelapse`

**Comment by kennethjiang** [comment]
Hmmm, I probably got it wrong here. It looks like `printer_storage` is ignored by git and should be provided by me...?

**Comment by th33xitus** [comment]
Yes, the `printer_storage` is not affected by git, but you shouldn't need to provide anything yourself. Even if you happen to delete the folder, its recreated once the container starts and everything is set up from scratch with the entry script.

Im not quite sure what exactly is happening. Every time you start the container, the entry script is run and therefor this function here as well: https://github.com/mainsail-crew/virtual-klipper-printer/blob/master/scripts/start.sh#L69
So the earlier cloning of moonraker-timelapse must have worked as it was able to successfully linkt the component part. But fails with the macro part. Permissions for klipper_config should also be set, as no "chowning" seems to happen before all of that.

**Comment by kennethjiang** [comment]
Thank you @th33xitus .

I re-cloned the repo from scratch and everything worked. So maybe the problem was caused by what I previously messed around with. Closing it as not reproducible.
