### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by pauhull** [mainsail-crew/virtual-klipper-printer#17]
When starting I receive this error:
![image](https://user-images.githubusercontent.com/22707808/221416226-af1f408f-3c8f-45a8-b518-aa17feee2ddb.png)

Because of the ``\r`` I suspect it has to do with CRLF line endings on Windows.

**Comment by th33xitus** [comment]
typical windows and git for windows issue:
https://troyready.com/blog/git-windows-dont-convert-line-endings.html
