### ISSUE TITLE
make: avr-gcc: No such file or directory

### ISSUE THREAD

**Issue by rollduck** [mainsail-crew/virtual-klipper-printer#25]
Hi, 

When I try to compile klipper for simulavr I receive an error message:
"printer@fbe65e03be03:~/klipper$ make
make: avr-gcc: No such file or directory
  Building out/autoconf.h
  Compiling out/src/sched.o
/bin/sh: 1: avr-gcc: not found
make: *** [Makefile:65: out/src/sched.o] Error 127"

Does someone know how to resolve this issue?

**Comment by dw-0** [comment]
The final container does not have the required packages installed anymore to build the firmware manually. This keeps image and container sizes significantly smaller. The intended way to run this container is, that the firmware gets build once during image building. When updates are necessary, simply rebuild the image and spin up a fresh container.

**Comment by rollduck** [comment]
Right, thank you for your help. It was obvious but I'm a newbie around containers so I thought that container was not "upgradeable" :)
