### ISSUE TITLE
/dev/serial/ missing

### ISSUE THREAD

**Issue by lexasidorov** [mainsail-crew/virtual-klipper-printer#32]
Hi!
Trying to virtualize klipper on a VM Ubuntu without any phisical printer. My goal is to test and customize klipper screen gui.

Just installed Klipper and KlipperScreen via KIAUH
Than installed virtual-klipper-printer
```
docker compose up -d --build
...
Container printer  Started 
```
Now I expect to find MCU serial in /dev/serial which is needed for klipper config

**Comment by meteyou** [comment]
Virtual Klipper printer is already Klipper/Moonraker + virtual board in one docker image. So you cannot install Klipper via kiauh to connect to it.
