### ISSUE TITLE
Docker container starts then immediately stops with error

### ISSUE THREAD

**Issue by NameOfTheDragon** [mainsail-crew/virtual-klipper-printer#34]
When trying to run this container, the container encounters an error and immediately stops. The error is:
![image](https://github.com/user-attachments/assets/c5887169-0679-4656-95eb-4ecfa2af4807)

**Comment by NameOfTheDragon** [comment]
See PR#35 for a fix.

**Comment by NameOfTheDragon** [comment]
I don't know why, but the PR isn't working. When I build the container from my fork, everything works fine; when I build it from yours, the problem comes back where one of the shell scripts has a bad line ending! I have run a file comparison on my two clones, and they are binary identical everywhere that matters, so I have no explanation.

**Comment by meteyou** [comment]
I think your PR doesn't fix the issue itself, it only fix this issue for new files or commits. But i have to double-check it.

**Comment by dw-0** [comment]
So that means a re-clone is required for that .gitattributes file to take effect?
